import { defineConfig } from "vite";
import preact from "@preact/preset-vite";
import { fileURLToPath, URL } from "node:url";
import { VitePWA } from "vite-plugin-pwa";

const src = (dir: string) => fileURLToPath(new URL(`./src/${dir}`, import.meta.url));

// https://vitejs.dev/config/
export default defineConfig({
  // Same aliases as tsconfig "paths" (previously generated by vite-aliases).
  resolve: {
    alias: {
      "@api": src("api"),
      "@assets": src("assets"),
      "@components": src("components"),
      "@hooks": src("hooks"),
      "@pages": src("pages"),
      "@store": src("store"),
      "@utils": src("utils"),
      "@": src(""),
    },
  },
  plugins: [
    preact(),
    VitePWA({
      registerType: "autoUpdate",
      includeAssets: [
        "favicon.ico",
        "apple-touch-icon.png",
        "android-chrome-192x192.png",
      ],
      manifest: {
        name: "Curiosta makers",
        short_name: "curiosta makers",
        description:
          "Curiosta makers is a comprehensive platform for managing makerspaces",
        theme_color: "#ffffff",
        icons: [
          {
            src: "android-chrome-192x192.png",
            sizes: "192x192",
            type: "image/png",
          },
          {
            src: "android-chrome-512x512.png",
            sizes: "512x512",
            type: "image/png",
          },
          {
            src: "maskable_icon_x512.png",
            sizes: "512x512",
            type: "image/png",
            purpose: "any",
          },
          {
            src: "maskable_icon_x512.png",
            sizes: "512x512",
            type: "image/png",
            purpose: "maskable",
          },
        ],
        background_color: "#ffffff",
        display: "standalone",
        scope: "/",
        start_url: "/",
        orientation: "portrait",
      },
    }),
  ],
});
